server:
  port: 10001
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: ttsx-prod

  application:
    name: ttsx-index
  web:
    resources:
      static-locations: [classpath:/META-INF/resources,classpath:/resources,classpath:/static,classpath:/templates]
logging:
  level:
    root: info
    com.ttsx: info
    org.springframewok.web: info
management:
  endpoints:
    web:
      exposure:
        include: "*"    # 暴露端点，* 是暴露全部端点